<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hgapeopledb"
 *
 * Auto generated by Extension Builder 1970-01-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'HGA People DB',
	'description' => 'Simple database for collect people with contact data, picture and info field.',
	'category' => 'plugin',
	'author' => 'Hans-Georg',
	'author_email' => 'Hans-Georg@althoff-fam.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '12.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '12.2.0-12.9.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);